kind: pipeline
type: docker
name: default

steps:
  - name: build
    build:
      image: vue/reef-tracker
      context: .
  - name: publish
    image: vue/reef-tracker

trigger:
  branch: master
  event:
    - push
    - pull_request
  repo:
    - reef-tracker
