kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm run test

trigger:
  branch: master
  event:
    - push
    - pull_request
  repo:
    - reef-tracker
